version: '3.4'

# networks:
#   localhost:
#     external: true

services:
    baseline:
        container_name: baseline
        image: cr.yandex/crppqtghoimgqql91veb/baseline:${tag}
        volumes:
            - '${PWD}/files:/app/files:delegated'
            - '${PWD}/tmp:/app/tmp:delegated'
            - '${PWD}/logs:/app/logs'